### ISSUE TITLE
shp::copy tests fail

### ISSUE THREAD

**Issue by lslusarczyk** [oneapi-src/distributed-ranges#120]
When running on PVC, e.g. by `srun -p QZ1J-SPR-PVC-2C -w sdp5259 ./shp-tests` or `srun -C GPU_QZ1B ./shp-tests`

the following tests fail
```
[  FAILED  ] CopyTest/1.dist2local_async, where TypeParam = sycl::_V1::usm_allocator<unsigned long long, (sycl::_V1::usm::alloc)2, 0ul>
[  FAILED  ] CopyTest/1.dist2local_sync, where TypeParam = sycl::_V1::usm_allocator<unsigned long long, (sycl::_V1::usm::alloc)2, 0ul>
[  FAILED  ] CopyTest/1.dist2local_async_can_interleave, where TypeParam = sycl::_V1::usm_allocator<unsigned long long, (sycl::_V1::usm::alloc)2, 0ul>
[  FAILED  ] CopyTest/1.dist2local_sliced_bothSides, where TypeParam = sycl::_V1::usm_allocator<unsigned long long, (sycl::_V1::usm::alloc)2, 0ul>
[  FAILED  ] CopyTest/1.dist2local_sliced_left, where TypeParam = sycl::_V1::usm_allocator<unsigned long long, (sycl::_V1::usm::alloc)2, 0ul>
[  FAILED  ] CopyTest/1.dist2local_sliced_right, where TypeParam = sycl::_V1::usm_allocator<unsigned long long, (sycl::_V1::usm::alloc)2, 0ul>
```
failing checks are
```
[----------] 6 tests from CopyTest/1, where TypeParam = sycl::_V1::usm_allocator<unsigned long long, (sycl::_V1::usm::alloc)2, 0ul>
[ RUN      ] CopyTest/1.dist2local_async
/nfs/site/home/lslusarc/src/distributed-ranges/test/gtest/shp/copy.cpp:14: Failure
Value of: equal(local_vec, typename TestFixture::LocalVec{1, 2, 3, 4, 5})
  Actual: false (
    [1, 2, 3, 4, 0]
    [1, 2, 3, 4, 5]
  )
Expected: true
[  FAILED  ] CopyTest/1.dist2local_async, where TypeParam = sycl::_V1::usm_allocator<unsigned long long, (sycl::_V1::usm::alloc)2, 0ul> (14 ms)
[ DISABLED ] CopyTest/1.DISABLED_local2dist_async
[ RUN      ] CopyTest/1.dist2local_sync
/nfs/site/home/lslusarc/src/distributed-ranges/test/gtest/shp/copy.cpp:32: Failure
Value of: equal(local_vec, typename TestFixture::LocalVec{1, 2, 3, 4, 5, 9})
  Actual: false (
    [1, 2, 3, 4, 0, 9]
    [1, 2, 3, 4, 5, 9]
  )
Expected: true
[  FAILED  ] CopyTest/1.dist2local_sync, where TypeParam = sycl::_V1::usm_allocator<unsigned long long, (sycl::_V1::usm::alloc)2, 0ul> (10 ms)
[ DISABLED ] CopyTest/1.DISABLED_local2dist_sync
[ RUN      ] CopyTest/1.dist2local_async_can_interleave
/nfs/site/home/lslusarc/src/distributed-ranges/test/gtest/shp/copy.cpp:58: Failure
Value of: equal(local_vec, typename TestFixture::LocalVec{1, 2, 3, 4, 2, 3, 4, 5})
  Actual: false (
    [1, 2, 3, 4, 2, 3, 4, 0]
    [1, 2, 3, 4, 2, 3, 4, 5]
  )
Expected: true
[  FAILED  ] CopyTest/1.dist2local_async_can_interleave, where TypeParam = sycl::_V1::usm_allocator<unsigned long long, (sycl::_V1::usm::alloc)2, 0ul> (15 ms)
[ DISABLED ] CopyTest/1.DISABLED_local2dist_async_can_interleave
[ RUN      ] CopyTest/1.dist2local_sliced_bothSides
/nfs/site/home/lslusarc/src/distributed-ranges/test/gtest/shp/copy.cpp:82: Failure
Value of: equal( local_vec, typename TestFixture::LocalVec{2, 3, 4, 5, 6, 7, 8, 9, 0, 0})
  Actual: false (
    [2, 3, 4, 5, 6, 0, 0, 0, 0, 0]
    [2, 3, 4, 5, 6, 7, 8, 9, 0, 0]
  )
Expected: true
[  FAILED  ] CopyTest/1.dist2local_sliced_bothSides, where TypeParam = sycl::_V1::usm_allocator<unsigned long long, (sycl::_V1::usm::alloc)2, 0ul> (10 ms)
[ RUN      ] CopyTest/1.dist2local_sliced_left
/nfs/site/home/lslusarc/src/distributed-ranges/test/gtest/shp/copy.cpp:93: Failure
Value of: equal(local_vec, typename TestFixture::LocalVec{2, 3, 4, 5, 6, 7, 8, 9, 10, 0})
  Actual: false (
    [2, 3, 4, 5, 6, 0, 0, 0, 0, 0]
    [2, 3, 4, 5, 6, 7, 8, 9, 10, 0]
  )
Expected: true
[  FAILED  ] CopyTest/1.dist2local_sliced_left, where TypeParam = sycl::_V1::usm_allocator<unsigned long long, (sycl::_V1::usm::alloc)2, 0ul> (12 ms)
[ RUN      ] CopyTest/1.dist2local_sliced_right
/nfs/site/home/lslusarc/src/distributed-ranges/test/gtest/shp/copy.cpp:104: Failure
Value of: equal( local_vec, typename TestFixture::LocalVec{1, 2, 3, 4, 5, 6, 7, 8, 9, 0})
  Actual: false (
    [1, 2, 3, 4, 5, 6, 0, 0, 0, 0]
    [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
  )
Expected: true
[  FAILED  ] CopyTest/1.dist2local_sliced_right, where TypeParam = sycl::_V1::usm_allocator<unsigned long long, (sycl::_V1::usm::alloc)2, 0ul> (10 ms)
```

**Comment by lslusarczyk** [comment]
Reason should be the same as described [here](https://github.com/oneapi-src/distributed-ranges/pull/60#issuecomment-1447527300).
I propose to change `copy` alg signature to take `remote_contiguous_range` instead of pair of iterators. We will have access to rank, we will be able to construct queue using this rank and it should work (I've fixed `fill` and `transform` this way)

**Comment by rscohn2** [comment]
> Reason should be the same as described [here](https://github.com/oneapi-src/distributed-ranges/pull/60#issuecomment-1447527300). I propose to change `copy` alg signature to take `remote_contiguous_range` instead of pair of iterators. We will have access to rank, we will be able to construct queue using this rank and it should work (I've fixed `fill` and `transform` this way)

Many of the std algorithms only take an iterator for a destination, including [transform](https://en.cppreference.com/w/cpp/algorithm/ranges/transform). You can get a rank from an iterator.

**Comment by BenBrock** [comment]
As discussed in our [JIRA ticket here](https://jira.devtools.intel.com/browse/CMPLRLLVM-45277), this is a bug in the Level Zero runtime and not a bug in our code.  For now, we should disable the USM shared tests.

None of the `shp` data structures currently store the rank in their iterator types.  This is because the concepts are designed to allow you to quickly turn a normal data structure into a remote data structure [by adding a rank method](https://github.com/oneapi-src/distributed-ranges/blob/main/include/dr/shp/device_vector.hpp).  Changing the codebase so that all iterators include a rank would require a significant amount of work.  (And I also think it is the wrong decision to do so because of a bug in Level Zero.)

I am not against adding [ranges versions of copy and fill](https://en.cppreference.com/w/cpp/algorithm/ranges/copy), although that is orthogonal and doesn't really fix these iterator versions.

**Comment by lslusarczyk** [comment]
> None of the shp data structures currently store the rank in their iterator types.

distributed iterators have segments and segments have ranks. I can change _copy_, _fill_ to use this information and issue memcpy to proper devices. Is using this rank against our design?

>  For now, we should disable the USM shared tests.

Unless it is a few weeks/month until USM is fixed and working I'm against disabling tests and having USM support in code at the same time. I would either workaround code to make tests pass or remove USM support. It seems they already implemented the fix but it may take long to wait for it to be in official oneAPI and to be stable. I'd like to fix _copy_ for now and enable all tests in USM and device_allocator - it seems possible without changing _copy_ signatures. Unless you object, I'd like to do it tomorrow.

It may be also a good move with respect to the fact that peer2peer is officially an optional feature.

**Comment by BenBrock** [comment]
> distributed iterators have segments and segments have ranks. I can change copy, fill to use this information and issue memcpy to proper devices. Is using this rank against our design?

No, my point is only that the iterator version of `copy` cannot depend on being able to access `rank` from the iterator with the current design.  This is because remote ranges are not required to have remote iterators, they can be any normal iterator type.  (The rank being stored with the *range*, not with the iterator.)

> Unless it is a few weeks/month until USM is fixed and working I'm against disabling tests and having USM support in code at the same time. I would either workaround code to make tests pass or remove USM support. It seems they already implemented the fix but it may take long to wait for it to be in official oneAPI and to be stable. I'd like to fix copy for now and enable all tests in USM and device_allocator - it seems possible without changing copy signatures. Unless you object, I'd like to do it tomorrow.

As far as I understand, the Level Zero runtime fix is going to be applied imminently.  (Although I'm not 100% sure of their timelines.)

> It may be also a good move with respect to the fact that peer2peer is officially an optional feature.

We had some discussion about this.  Our current plan is to prioritize peer-to-peer, as that is the primary case where users would be using our code.  Peer-to-peer will be available on all systems with Xe Link.  We still need to investigate whether peer-to-peer is available over PCIe with consumer GPUs.

**Comment by lslusarczyk** [comment]
> This is because remote ranges are not required to have remote iterators, they can be any normal iterator type.

In this case we could require user to use range-base (not iterator based) API, so our code can know the rank. Does it make sense?

Assuming bug is fixed. We are then allowed to create queue associated with context only, no special device. Will it run with optimal performance? Is L0/sycl going to know what device copied memory is located at and execute memcpy on right GPU? Or will it be a randomly selected GPU (or worse - default one) which will be doing peer2peer comunication with source and destination?
Do you know where I can learn about this?

In case of thousands of GPUs (Aurora or system like this) is it also valid that peer2peer can be working between all GPUs? (I have no idea about this, I'm still learning how HPC works - please share your opinion or where you would start to look for the answer)

> Our current plan is to prioritize peer-to-peer

I am all the time thinking whether to use of sycl::queue with and without specifying the device. What I understand from [this comment](https://github.com/oneapi-src/distributed-ranges/pull/119#discussion_r1136860050) memcpy when used on que with device may issue p2p if supported and go through host if not.
What does it mean "prioritize peer-to-peer"? Writing code using queues without devices? Something else?

> Xe Link ...

Where I can best learn what it is?

**Comment by lslusarczyk** [comment]
Fixed by disabling USM shared allocator.
