### ISSUE TITLE
Make CI testing not less than it tested at old non-public repo.

### ISSUE THREAD

**Issue by rscohn2** [oneapi-src/distributed-ranges#16]
(description created by @lslusarczyk)
Here is CI definition on old repo: [.github/workflows/ci.yml on intel-sandbox](https://github.com/intel-sandbox/libraries.runtimes.hpc.dds.distributed-ranges/blob/main/.github/workflows/ci.yml)
Here is how it looks like on new one: [.github/workflows/ci.yml on oneapi-src](https://github.com/oneapi-src/distributed-ranges/blob/feature/shp-rv3/.github/workflows/ci.yml)

Task is to
1. check if all (compilers, modes) which was tested previously is also tested now - add a comment here about it
2. if there is something which is not tested now but was before - try to make it being tested.

**Comment by lslusarczyk** [comment]
Accrding to @haichangsi, CIs are the same except one line 
`cmake -B build -DENABLE_SYCL_MPI=on -DENABLE_SYCL=on`
