### ISSUE TITLE
sliding_view for 1D vector, use in 1D stencil

### ISSUE THREAD

**Issue by lslusarczyk** [oneapi-src/distributed-ranges#233]
From slack discussion with @rscohn2 :
If we are going to do a stencil where transform/foreach can pass a view to the function, then we should get it working for 1d stencil first. There is already a suitable view: [slide_view](https://en.cppreference.com/w/cpp/ranges/slide_view)

Here is [the sliding view implementation of 1d stencil](https://github.com/oneapi-src/distributed-ranges/blob/main/examples/mhp/stencil-slide.cpp)
It is very close to what we have in 2D. We would have to generalize subrange and sliding to multi-dimensions. The sliding view has 2 advantages over how you have it now:
- windows size is explicit
- subrange and sliding are independent views vs the subrange in your example

**Comment by BenBrock** [comment]
I think we do want to have `slide_view`.  We might even want a multi-dimensional `slide_view`.  However, I think the "stencil point" syntax that @mateuszpn was showing is also something we want.

Stencils are typically written in terms of coordinates---both positive and negative---relative to the point that you are processing.  I think that's probably more useful to stencil writers than the sliding view.

A simple five point stencil:

```cpp
auto stencil_op =
  [](auto&& p) {
    p[{0, 0}] += 0.5 * p[{0, 1}] + 0.5 * p[{1, 0}] + 0.5 * p[{-1, 0}] + 0.5 * p[{0, -1}];
  }
```

Becomes a bit more difficult to express with a window, where you now need to orient the stencil around the `{w.shape()[0] / 2, w.shape()[1] / 2}`'th index.

**Comment by rscohn2** [comment]
> Becomes a bit more difficult to express with a window, where you now need to orient the stencil around the `{w.shape()[0] / 2, w.shape()[1] / 2}`'th index.

It is true that for the typical 5 point stencil code making 0 be the center of the window is more intuitive than making 0 be the left side of the window. It is probably something the C++ committee considered for `slide_view`. Some potential issues with 0 as center are:
* what if I have a stencil that updates element 0, and references element 0-3?
* iterators with negative indices? Is there precedence for that?
* making the value be an iterator vs a range

Another issue with the current matrix is that it combines several concepts that could be orthogonal:
* 2d view
* subrange
* window view into a range

The current view is oriented around a specific type of stencil. One approach might be to say that we will develop orthogonal views in the long term, and when we do that, we will still support the current view, but possibly implement it on top of the orthogonal views.

**Comment by lslusarczyk** [comment]
> what if I have a stencil that updates element 0, and references element 0-3?

Moreover there may be even size of window and there is no natural center.
I think our sliding view needs an extra parameter in addition to sliding view size. This is location of center. This is because we need to decide which element of slide view goes to which segment. Alternative is to include same slide element in two segments, but this looks as ugly and error prone solution.

Problem example is:
dv: [1,2,3,a,b,c,A,B,C] with 1,2,3 and a,b,c and A,B,C being in different devices (I, II, III).
then slide_view(3) is: [ [1,2,3], [2,3,a], [3,a,b], [a,b,c], [b,c,A], [c,A,B], [A,B,C] ]

then segments can be

I: [1,2,3], [2,3,a], [3,a,b]
II: [a,b,c], [b,c,A], [c,A,B]
III: [A,B,C]
if center is the first element

I: [1,2,3], [2,3,a]
II:  [3,a,b], [a,b,c], [b,c,A]
III: [c,A,B], [A,B,C]
if center is the second element

I: [1,2,3], 
II:  [2,3,a], [3,a,b], [a,b,c]
III: [b,c,A], [c,A,B], [A,B,C]
if center is the third element

I'df like to introduce parameter to our slide_view determining where center is (better name maybe main_element). Best default seems to me be 0, or as good as 0 there may be no default. (size+1)/2 as default center is not a good choice, because of even sizes.

This may allow us to make negative indices if we decide we want them.

Any comments, objections?

**Comment by lslusarczyk** [comment]
of course an assertion is going to ensure halo bounds of dv are enough to serve given slide size and center

**Comment by rscohn2** [comment]
> dv: [1,2,3,a,b,c,A,B,C] with 1,2,3 and a,b,c and A,B,C being in different devices (I, II, III).
> then slide_view(3) is: [ [1,2,3], [2,3,a], [3,a,b], [a,b,c], [b,c,A], [c,A,B], [A,B,C] ]

ok. halo size is 1. means hb.prev=1, hb.next=1

Segments are: 
``[ [1,2,3], [a, b, c], [A, B, C]]``
segment storage is size 5 (segment.size() + hb.prev + hb.next), and segments start at offset hb.prev in storage
``[[0, 1, 2, 3, 0], [0, a, b, c, 0], [0, A, B, C, 0]]``

After halo exchange:
``[[0, 1, 2, 3, a], [3, a, b, c, A], [c, A, B, C, 0]]``

Parallel execution of the slide view determined by which process has every element of the slide view:
Process 0: [1,2,3], [2, 3, a]
Process 1: [3, a, b], [a, b, c], [b, c, A]
Process 2: [c, A, B], [A, B, C]

For the slide_view stencil I wrote, you do not modify the slide view.
If you want to modify elements of the slide view and you have a halo size of 1, then you cannot modify the 1st or last element of a slide view.

WIth the matrix view, you cannot modify offsets +1,-1. 

I don't see the need for a center specification.

**Comment by lslusarczyk** [comment]
I see your point. So you suggest to not support _n_ parameter which standard [slide_view](https://en.cppreference.com/w/cpp/ranges/slide_view) allows user to pass, but basically your suggestion is that dist-ranges slide_view uses _n_ that always equals to `hb.prev + 1 + hb.next` of underlying distributed container. In this case centre is indeed well defined.

What I considered is that we allow user to specify _n_ (being no greater than `hb.prev + 1 + hb.next`). In this case, if _n_ is smaller you need a way to define centre in order to properly divide _slide_view_ (which is a range of ranges) into segments.

So our slide_view should either
- mask _n_ parameter (not allow to use it in constructor), or
- allow to specify another number beside _n_ (it may be _n_ with _center_, or _left_side_size_ with _right_side_size_)

Please confirm that you prefer first solution over the second. Or correct me if my understanding is wrong.

> For the slide_view stencil I wrote, you do not modify the slide view.

Stencil-slide is working over std::vector, not distributed one (no problem with segments). stencil-1d does not use real slide_view. Its user-operator is getting raw pointer as input (not a range with begin/end). Just its indices are legal between -hb.prev and +hb.next. As I understand we want to provide user with a way of writing operator that will receive range instead of raw pointer.

**Comment by lslusarczyk** [comment]
In fact, we could provide both versions. Have slide_view with two constructors
-  without _n_ and 
- ctor with two numbers (left_side_size, right_side_size).

**Comment by rscohn2** [comment]
I was confused about what you meant by center, but think I understand now:
* general halo specification is `halo(left, center, right)`, `halo(n)` is the same as `halo(n, 1, n)`. `halo()` is same as `halo(0, 1, 0)`
* `slide_view(range, left, center, right)` Like `std::slide_view`, it is a range of overlapping ranges of the underlying range (base). The size of the range is `left + center + right`. Modifying left or right is undefined behavior. If the base has a halo: `halo(left_base, center_base, right_base)` then it is an error if `left_base >= left && center_base >= center && right_base >= right` is not true.
* `slide_view()` gets `left, center, right` from the base
* `slide_view(n)` gets `left, center, right` from the base. It is an error if `n == left + center + right` is not true.

Is this description consistent with what you are proposing?

The 1d version of the view that Mateusz is working on now could be implemented on top of this `slide_view` with a `transform` that takes a view and returns an iterator for the center.

I think this can support general stencil, but would be reluctant to start on it until we had some definite examples in mind. I don't think it is needed for any of the potential benchmarks we are considering. How do you want to proceed?

**Comment by lslusarczyk** [comment]
It's hard to say if we understand the design in the same way without whiteboard and meeting I think. But it seems we are close at least :) [This](https://github.com/lslusarczyk/distributed-ranges/commit/ae8bd50bb489e317523b3371f6d29f10e6e3b25b#diff-a260aebfe315c3fc6188d035ba03f9ae23e5ad0beca65528f27c439a1f817a50R145) and [this](https://github.com/lslusarczyk/distributed-ranges/commit/ae8bd50bb489e317523b3371f6d29f10e6e3b25b#diff-3ab43e985fed9dae0347e932045b547e2192baa2faea062346fb7c1a9ed4f3feR123) are main changes (segments & local methods) which I'm trying to make working and maybe they will more precisely explain my idea (disclaimer - the branch is highly WIP). I need to stop due to vacations. I'm back 10th May and will be happy to continue this job as I'm enjoying a lot designing this view and looking how it starts to work. Let's schedule 1:1 on 10th May and talk. Can this task wail till then?

**Comment by rscohn2** [comment]
We can pick it up after your return. If you are close to having some code I could see, that would clear up any ambiguities.
