### ISSUE TITLE
mhp::halo exchange with prev!=next fails with MPI_ERR_TRUNCATE

### ISSUE THREAD

**Issue by lslusarczyk** [oneapi-src/distributed-ranges#293]
exposing test added at branch: https://github.com/oneapi-src/distributed-ranges/compare/main...lslusarczyk:distributed-ranges:halo_prev_neq_next_bug

to expose
```
cmake -S . -B build
cmake --build build --target mhp-tests-3
ctest --test-dir build -R mhp-tests-3-only
```

**Comment by mateuszpn** [comment]
PR #324
