### ISSUE TITLE
fill

### ISSUE THREAD

**Issue by rscohn2** [oneapi-src/distributed-ranges#94]

**Comment by rscohn2** [comment]
Common test is written. Disabled in `shp-tests.cpp`

@BenBrock: I did not see an implementation in SHP?

**Comment by BenBrock** [comment]
Correct, there's no implementation of `shp::fill` in `shp`.  I think I might have seen someone on the Polish side taking a look? @lslusarczyk

If not, it would be a good algorithm for someone to get their feet wet with.  (Essentially call `fill_async` on each segment.)

**Comment by lslusarczyk** [comment]
Indeed there is unfinished _fill_ which only works on a one segment. I think its a good task for @haichangsi (like iota). I've assigned him to it.
